### ISSUE TITLE
Check mode not working correctly

### ISSUE THREAD

**Issue by marianadiaz179** [irunasroot/action-awx-template#14]
When I launch the action from github action using the following code

```yaml
- name: Launch AWX/AAP Template in Check Mode
        id: launch_awx_check
        uses: irunasroot/action-awx-template@v1
        with:
          controller_url: http://<url>
          controller_username: ${{ env.SECRETUSERNAME }}
          controller_password: ${{ env.SECRETPASSWORD }}
          job_template_id: <id>
          job_type: check
```

This should change the job type of job 141 which is by default in "run"  to "check" mode, however, it is running in "run" mode and applying the changes, which is not desired.
