### ISSUE TITLE
Extra vars are not being passed correctly

### ISSUE THREAD

**Issue by marianadiaz179** [irunasroot/action-awx-template#15]
When I launch the action from github action using the following code

```yaml
- name: Launch AWX/AAP Template in Check Mode
        id: launch_awx_check
        uses: irunasroot/action-awx-template@v1
        with:
          controller_url: http://<URL>
          controller_username: ${{ env.SECRETUSERNAME }}
          controller_password: ${{ env.SECRETPASSWORD }}
          job_template_id: <id>
          job_type: check
         extra_vars: '{"virtual_server_selected": ["${{ github.event.repository.name }}"]}'
```

This should change the extra vars to what is defined in the script but it isn't passing any extra vars so the job is failing

![image](https://github.com/user-attachments/assets/daef363e-ebcf-405c-89ac-4a7b72f71043)
